version: '3'

services:
  demo:
    image: demo
    container_name: demo
    image: demo:1.0.0
    build:
        context: .
        target: development
        dockerfile: ./Dockerfile
    command: npm run start:debug
    restart: on-failure
    working_dir: /home/demo
    volumes:
      - ./:/home/demo
      - /home/demo/node_modules
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - "db"
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'crud'


  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
    volumes: 
      - ~/docker/mysql-data:/var/lib/mysql
